# -*- coding: utf-8 -*-
"""David first app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncdNsLN4W4V1IBMrjzql-zlaKHZ6VkXR
"""

import streamlit as st

st.title("Netlix 18+ Hollywood Movies Censoring System")

age = st.number_input("Enter your age:", min_value=0, steps=1)

if st.button("Check Eligibilty"):
  if age <13:
    st.warning ("you are a kid, you cannot watch Netflix 18+ movies!")

  elif age >=13 and age <18:
    st.warning("you are a teenager,you cannot watch Netflix 18+ movies!")

  else:
    st.success("you are an adult,you can watch 18+ movies!")


st.markdown("Developed by David Olusomidomo")













